//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCrypt.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access permission.
        /// </summary>
        public static string AccessPermission {
            get {
                return ResourceManager.GetString("AccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        public static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel editing?.
        /// </summary>
        public static string CancelEditing {
            get {
                return ResourceManager.GetString("CancelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum.
        /// </summary>
        public static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose or drag-and-drop a file first.
        /// </summary>
        public static string ChooseAFileFirst {
            get {
                return ResourceManager.GetString("ChooseAFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file....
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonants.
        /// </summary>
        public static string Consonants {
            get {
                return ResourceManager.GetString("Consonants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password.
        /// </summary>
        public static string CopyPassword {
            get {
                return ResourceManager.GetString("CopyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password file could not be saved!.
        /// </summary>
        public static string CouldNotSaveStorage {
            get {
                return ResourceManager.GetString("CouldNotSaveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password! Please try again!.
        /// </summary>
        public static string CryptographicException {
            get {
                return ResourceManager.GetString("CryptographicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryptions using DPAPI are bound to this account or machine. Files can be only decrypted by using this account/machine! This method works best with small files..
        /// </summary>
        public static string DpApiInfo {
            get {
                return ResourceManager.GetString("DpApiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop.
        /// </summary>
        public static string DragAndDrop {
            get {
                return ResourceManager.GetString("DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while dropping a file..
        /// </summary>
        public static string DragAndDropError {
            get {
                return ResourceManager.GetString("DragAndDropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dropped file is invalid. Please verify that it is a single file..
        /// </summary>
        public static string DragAndDropInvalidFile {
            get {
                return ResourceManager.GetString("DragAndDropInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one file can be encrypted or decrypted at the same time..
        /// </summary>
        public static string DragAndDropSingleFile {
            get {
                return ResourceManager.GetString("DragAndDropSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        public static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Password Manager.
        /// </summary>
        public static string EnablePasswordManager {
            get {
                return ResourceManager.GetString("EnablePasswordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something did not work while encrypting/decrypting &quot;{0}&quot;. Try a different password or algorithm..
        /// </summary>
        public static string EncryptionDecryptionFailed {
            get {
                return ResourceManager.GetString("EncryptionDecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string EnglishAmerican {
            get {
                return ResourceManager.GetString("EnglishAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for your password storage. You can change this name anytime..
        /// </summary>
        public static string EnterAStorageName {
            get {
                return ResourceManager.GetString("EnterAStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while exporting: {0}.
        /// </summary>
        public static string ErrorWhileExporting {
            get {
                return ResourceManager.GetString("ErrorWhileExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string Everything {
            get {
                return ResourceManager.GetString("Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Entry.
        /// </summary>
        public static string ExampleEntry {
            get {
                return ResourceManager.GetString("ExampleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a example password manager entry. Click on the eye icon above to display its password. You can delete this entry..
        /// </summary>
        public static string ExampleEntryComment {
            get {
                return ResourceManager.GetString("ExampleEntryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string FileDestination {
            get {
                return ResourceManager.GetString("FileDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Germany).
        /// </summary>
        public static string GermanGerman {
            get {
                return ResourceManager.GetString("GermanGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal.
        /// </summary>
        public static string Hexadecimal {
            get {
                return ResourceManager.GetString("Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover here to display..
        /// </summary>
        public static string HoverHereToDisplay {
            get {
                return ResourceManager.GetString("HoverHereToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphens.
        /// </summary>
        public static string Hyphens {
            get {
                return ResourceManager.GetString("Hyphens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the password file. Please try again. Error: {0}.
        /// </summary>
        public static string IOException {
            get {
                return ResourceManager.GetString("IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string LowerCase {
            get {
                return ResourceManager.GetString("LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry.
        /// </summary>
        public static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password consists of common word or a variation..
        /// </summary>
        public static string PasswordContainsCommonWord {
            get {
                return ResourceManager.GetString("PasswordContainsCommonWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        public static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Manager.
        /// </summary>
        public static string PasswordManager {
            get {
                return ResourceManager.GetString("PasswordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password manager window is already open..
        /// </summary>
        public static string PasswordManagerAlreadyOpen {
            get {
                return ResourceManager.GetString("PasswordManagerAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name for this password storage..
        /// </summary>
        public static string PasswordManagerNewName {
            get {
                return ResourceManager.GetString("PasswordManagerNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal! Please try again..
        /// </summary>
        public static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords will stay only 10 seconds in clipboard!.
        /// </summary>
        public static string PasswordsStay10SecondsInClipboard {
            get {
                return ResourceManager.GetString("PasswordsStay10SecondsInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password will be removed after 5 seconds..
        /// </summary>
        public static string PasswordWillBeRemovedIn5Seconds {
            get {
                return ResourceManager.GetString("PasswordWillBeRemovedIn5Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string ReallyDeleteEntry {
            get {
                return ResourceManager.GetString("ReallyDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restart LCrypt?.
        /// </summary>
        public static string ReallyRestart {
            get {
                return ResourceManager.GetString("ReallyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart to apply changes.
        /// </summary>
        public static string RestartToApplyChanges {
            get {
                return ResourceManager.GetString("RestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string Strong {
            get {
                return ResourceManager.GetString("Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was successfully decrypted to &quot;{1}&quot; with algorithm {2}..
        /// </summary>
        public static string SuccessfullyDecrypted {
            get {
                return ResourceManager.GetString("SuccessfullyDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was successfully encrypted to &quot;{1}&quot; with algorithm {2}..
        /// </summary>
        public static string SuccessfullyEncrypted {
            get {
                return ResourceManager.GetString("SuccessfullyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash information was successfully exported..
        /// </summary>
        public static string SuccessfullyExported {
            get {
                return ResourceManager.GetString("SuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account.
        /// </summary>
        public static string ThisAccount {
            get {
                return ResourceManager.GetString("ThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer.
        /// </summary>
        public static string ThisComputer {
            get {
                return ResourceManager.GetString("ThisComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your Master Password..
        /// </summary>
        public static string TypeInMasterPassword {
            get {
                return ResourceManager.GetString("TypeInMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your Master Password again..
        /// </summary>
        public static string TypeInMasterPasswordAgain {
            get {
                return ResourceManager.GetString("TypeInMasterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again. Error: {0}.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string UpperCase {
            get {
                return ResourceManager.GetString("UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames.
        /// </summary>
        public static string Usernames {
            get {
                return ResourceManager.GetString("Usernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong.
        /// </summary>
        public static string VeryStrong {
            get {
                return ResourceManager.GetString("VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very weak.
        /// </summary>
        public static string VeryWeak {
            get {
                return ResourceManager.GetString("VeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit LCrypt on GitHub..
        /// </summary>
        public static string VisitLCryptOnGitHub {
            get {
                return ResourceManager.GetString("VisitLCryptOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocals.
        /// </summary>
        public static string Vocals {
            get {
                return ResourceManager.GetString("Vocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string Weak {
            get {
                return ResourceManager.GetString("Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the LCrypt Password Manager! First, you have to set your Master Password. Without it, you can&apos;t decrypt your password file, so be sure to remember it!.
        /// </summary>
        public static string WelcomeToPasswordManager {
            get {
                return ResourceManager.GetString("WelcomeToPasswordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write an Email to Loris156..
        /// </summary>
        public static string WriteAnEmailToLoris156 {
            get {
                return ResourceManager.GetString("WriteAnEmailToLoris156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
